# kita dapat mendefinisikan beberapa dokumen YAML dalam satu file dan memisahkan komponen-komponen ini menggunakan tanda ---

# semua konfigurasi saya dapat memisahkan mereka menggunakan tanda --- dan ini adalah cara yang baik untuk mengelola konfigurasi saya

apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquito-config-file
data:
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001


# tanda ini untuk memisahkan document yaml
---
apiVersion: v1
kind: NginxMap
metadata:
  name: nginx-config-file
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;
    events {
      worker_connections 1024;
    }
    http {
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;
      sendfile            on;
      tcp_nopush          on;
      tcp_nodelay         on;
      keepalive_timeout   65;
      types_hash_max_size 2048;
      include             /etc/nginx/mime.types;
      default_type        application/octet-stream;
      include /etc/nginx/conf.d/*.conf;
      server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;
        include /etc/nginx/default.d/*.conf;
        location / {
        }
        error_page 404 /404.html;
        location = /40x.html {
        }
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        }
      }
    }


